class TintaAcabamento < ApplicationRecord
  belongs_to :tinta_produto

  INTEGRATION = {
    "ESM SINT EXTRA RAPIDO" => 'ESM%SINTETICO%BRILHANTE',
    "ESMALTE SINT EXTRA RAPIDO" => 'ESM%SINTETICO%BRILHANTE',
    "SUP.COBERT.FOSCO[NOVO]" => 'SUPER%COBERTURA%FOSCO',
    "SUPER COBERTURA FOSCO" => 'SUPER%COBERTURA%FOSCO',
    "SUP.COBERT.SB[NOVO]" => 'SUPER%COBERTURA%SB',
    "SUPER COBERTURA SB" => 'SUPER%COBERTURA%SB',
    "BASE SELADOR OURO" => 'BASE SELADOR OURO',
    "RAFIATTO RUSTICO" => 'RAFIATTO%RUSTICO',
    "RAFIATTO CLASSIC" => 'RAFIATTO%CLASSIC',
    "TEXTURA QUARTZO HIDROREP" => 'TEXTURA%QUARTZO%HIDROREP',
    "ESM SINTETICO [ANTIGO]" => nil,
    "SUP.COBERT.FOSCO[ANTIGO]" => nil,
    "ESMALTELIT" => "ESMALTELIT",
    "SUP.COBERT.SB[ANTIGO]" => nil,
    "OURO FOSCO [ANTIGO]" => nil,
    "OURO FOSCO [NOVO]" => "OURO%FOSCO%LANÇAMENTO",
    "OURO FOSCO" => "OURO%FOSCO%LANÇAMENTO",
    "OURO ACETINADO [ANTIGO]" => "OURO%ACET%ANTIGA",
    "OURO ACETINADO [NOVO]" => "OURO%ACET%LANÇAMENTO",
    "OURO ACETINADO" => "OURO%ACET%LANÇAMENTO",
    "OURO SEMIBRILHO [ANTIGO]" => "OURO%SB%ANTIGA",
    "OURO SEMIBRILHO [NOVO]" => "OURO%SB%LANÇAMENTO",
    "OURO SEMIBRILHO" => "OURO%SB%LANÇAMENTO",
    "OURO EMBORRACHADA" => "OURO EMBORRACHADA",
    "COBRE BEM" => 'COBRE BEM',
    "PINTA MAIS 300m²" => "PINTA MAIS 300m%",
    "SUPER COBERTURA MAIS" => 'SUPER COBERTURA MAIS',
    "TINTA EPOXI BASE AGUA" => 'TINTA EPOXI BASE AGUA'
  }

  # INTEGRATION = {
  #   "ESM SINT EXTRA RAPIDO" => 'ESM%SINTETICO%BRILHANTE',
  #   "SUP.COBERT.FOSCO[NOVO]" => 'SUPER%COBERTURA%FOSCO',
  #   "SUP.COBERT.SB[NOVO]" => 'SUPER%COBERTURA%SB',
  #   "BASE SELADOR OURO" => 'BASE SELADOR OURO',
  #   "RAFIATTO RUSTICO" => 'RAFIATTO%RUSTICO',
  #   "RAFIATTO CLASSIC" => 'RAFIATTO%CLASSIC',
  #   "TEXTURA QUARTZO HIDROREP" => 'TEXTURA%QUARTZO%HIDROREP',
  #   "ESM SINTETICO [ANTIGO]" => nil,
  #   "SUP.COBERT.FOSCO[ANTIGO]" => nil,
  #   "ESMALTELIT" => "ESMALTELIT",
  #   "SUP.COBERT.SB[ANTIGO]" => nil,
  #   "OURO FOSCO [ANTIGO]" => nil,
  #   "OURO FOSCO [NOVO]" => "OURO%FOSCO%LANÇAMENTO",
  #   "OURO ACETINADO [ANTIGO]" => "OURO%ACET%ANTIGA",
  #   "OURO ACETINADO [NOVO]" => "OURO%ACET%LANÇAMENTO",
  #   "OURO SEMIBRILHO [ANTIGO]" => "OURO%SB%ANTIGA",
  #   "OURO SEMIBRILHO [NOVO]" => "OURO%SB%LANÇAMENTO",
  #   "OURO EMBORRACHADA" => "OURO EMBORRACHADA",
  #   "COBRE BEM" => 'COBRE BEM',
  #   "PINTA MAIS 300m²" => "PINTA MAIS 300m%",
  #   "SUPER COBERTURA MAIS" => 'SUPER COBERTURA MAIS',
  #   "TINTA EPOXI BASE AGUA" => 'TINTA EPOXI BASE AGUA'
  # }

end
